FROM alpine:3.4

ENV USER root
WORKDIR /usr/docker

RUN mkdir -p /usr/docker /var/log/docker/

COPY bin/web /usr/docker/web
COPY entry.sh /entry.sh

# needed in order for go binary to work.
RUN mkdir /lib64 && ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2

RUN chmod 755 /entry.sh

CMD ["/entry.sh"]
