FROM golang:1.7

# RUN go get  github.com/golang/lint/golint \
#             github.com/mattn/goveralls \
#             golang.org/x/tools/cover

ENV USER root
WORKDIR /go/

COPY . ./
RUN mkdir -p bin

CMD ["/compile.sh"]
